In [1]:
import torch

### torch.rand used to generate torch(array) with random values

In [2]:
x = torch.rand(3)

In [3]:
print(x)

tensor([0.4925, 0.9785, 0.2985])


we can intialize torch with differnt sizes

In [5]:
x = torch.rand(3,3)
print(x)

tensor([[0.2261, 0.2234, 0.1478],
        [0.6433, 0.0572, 0.2219],
        [0.1493, 0.1769, 0.2544]])


torch.empty() used to intialize torch with no values

In [6]:
x = torch.empty(3)
print(x)

tensor([-1.9549e-03,  1.4503e-42,  0.0000e+00])


torch.zeros() fills the torch with zeros
torch.ones() fills the torch with ones

In [7]:
zeros = torch.zeros(2,2)
ones = torch.ones(3,3,3)
print(zeros)
print(ones)

tensor([[0., 0.],
        [0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


dtype is used to know the type
by defualt the data type is float32

In [8]:
print(x.dtype)

torch.float32


we can spcify a certain type to the torch for example: dtype=torch.int

In [9]:
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

torch.int32


### .size() used to know the size of the torch

In [10]:
print(x.size())

torch.Size([2, 2])


### to add two tensors

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z1 = x + y 
# orrrrrrrrr
z2 = torch.add(x,y)
# the result will be the same
print(z1)
print(z2)

tensor([[0.8978, 0.2639],
        [1.5585, 0.7205]])
tensor([[0.8978, 0.2639],
        [1.5585, 0.7205]])


y.add_(x) used to modify the values of y to (y + x) inplace

In [12]:
print("y before addition",y)
y.add_(x)
print("y after addition",y)

y before addition tensor([[0.0433, 0.0225],
        [0.6716, 0.0155]])
y after addition tensor([[0.8978, 0.2639],
        [1.5585, 0.7205]])


### subtract will be the similar to addition

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z1 = y - x 
# orrrrrrrrr
z2 = torch.sub(y,x)
# the result will be the same
print(z1)
print(z2)
print("y before subtraction",y)
y.sub_(x)
print("y after subtraction",y)

tensor([[-0.0994, -0.1993],
        [-0.1569,  0.0103]])
tensor([[-0.0994, -0.1993],
        [-0.1569,  0.0103]])
y before subtraction tensor([[0.7292, 0.7361],
        [0.1151, 0.2978]])
y after subtraction tensor([[-0.0994, -0.1993],
        [-0.1569,  0.0103]])


### multiplication in pytorch

In [22]:
x = torch.rand(2,2)
y = torch.rand(2,2) 
z1 = torch.mul(y,x)
print("torch.mul(y,x) ",z1)
z2 = x * y
print("y * x", z2)
print("y before multiplication",y)
# inplace y 
y.mul_(x)
print("y after multiplication",y)

torch.mul(y,x)  tensor([[0.8786, 0.6150],
        [0.0873, 0.1977]])
y * x tensor([[0.8786, 0.6150],
        [0.0873, 0.1977]])
y before multiplication tensor([[0.9591, 0.9606],
        [0.3273, 0.9274]])
y after multiplication tensor([[0.8786, 0.6150],
        [0.0873, 0.1977]])


### division

In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2) 
z1 = torch.div(y,x)
print(z1)
z2 = y/x
print(z2)
print("y before division",y)
# inplace y 
y.div_(x)
print("y after division",y)

tensor([[5.2843, 0.4428],
        [0.7179, 1.8030]])
tensor([[5.2843, 0.4428],
        [0.7179, 1.8030]])
y before division tensor([[0.5908, 0.3676],
        [0.6815, 0.8736]])
y after division tensor([[5.2843, 0.4428],
        [0.7179, 1.8030]])


In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2) 
z1 = torch.mul(y,x)
print("torch.mul(y,x) ",z1)
z2 = x * y
print("y * x", z2)

torch.mul(y,x)  tensor([[0.3317, 0.0439],
        [0.1589, 0.0041]])
y * x tensor([[0.3317, 0.0439],
        [0.1589, 0.0041]])


## slicing

In [26]:
x = torch.rand(5,3)
print(x)
# all rows but only the column zero
print(x[:, 0])
# all columns but row number 1
print(x[1, :])
# getting one element
print(x[1,1])
# .item() used to get the value 
print(x[1,1].item())

tensor([[0.2943, 0.7123, 0.0922],
        [0.9528, 0.8552, 0.7189],
        [0.6934, 0.5603, 0.7513],
        [0.1757, 0.2859, 0.0901],
        [0.0851, 0.1350, 0.9132]])
tensor([0.2943, 0.9528, 0.6934, 0.1757, 0.0851])
tensor([0.9528, 0.8552, 0.7189])
tensor(0.8552)
0.8551594018936157


### reshaping

In [28]:
x = torch.rand(4,4)
print(x)
y = x.view(16) # number of elements must be the same
print(y)
# inplace reshaping 
print(x.reshape(16))

tensor([[0.3743, 0.0719, 0.5255, 0.3576],
        [0.8095, 0.8874, 0.6651, 0.0505],
        [0.4099, 0.3033, 0.3814, 0.7799],
        [0.4221, 0.4243, 0.3112, 0.4511]])
tensor([0.3743, 0.0719, 0.5255, 0.3576, 0.8095, 0.8874, 0.6651, 0.0505, 0.4099,
        0.3033, 0.3814, 0.7799, 0.4221, 0.4243, 0.3112, 0.4511])
tensor([0.3743, 0.0719, 0.5255, 0.3576, 0.8095, 0.8874, 0.6651, 0.0505, 0.4099,
        0.3033, 0.3814, 0.7799, 0.4221, 0.4243, 0.3112, 0.4511])


if we don't want 1 dimension so we can do

In [31]:
x = torch.rand(4,4)
print(x)
y = x.view(-1,8) # and pytorch will do it automatically determine the right size
print(y)
print(y.size())
m = x.view(-1,2)
print(m)
print(m.size())

tensor([[0.9072, 0.3605, 0.6097, 0.5635],
        [0.8124, 0.0701, 0.3118, 0.9063],
        [0.6803, 0.5625, 0.9576, 0.0460],
        [0.8683, 0.0341, 0.2139, 0.0769]])
tensor([[0.9072, 0.3605, 0.6097, 0.5635, 0.8124, 0.0701, 0.3118, 0.9063],
        [0.6803, 0.5625, 0.9576, 0.0460, 0.8683, 0.0341, 0.2139, 0.0769]])
torch.Size([2, 8])
tensor([[0.9072, 0.3605],
        [0.6097, 0.5635],
        [0.8124, 0.0701],
        [0.3118, 0.9063],
        [0.6803, 0.5625],
        [0.9576, 0.0460],
        [0.8683, 0.0341],
        [0.2139, 0.0769]])
torch.Size([8, 2])


## converting from numpy to tensors and vise versa

In [32]:
import numpy as np

In [39]:
#### from tensor to numpy
print("from tensor to numpy")
a = torch.ones(5)
print("the tensor is: ",a)
b = a.numpy()
print("the numpy array is: ", b)
## if we are at cpu and change the tensor a -> b will be effect 
## because they share the same memory location
a.add_(1)
print("a after adding: ",a)
print("b after adding: ", b)

print("##########################################")
### from numpy to tensor
print("from numpy to tensor")
numpyArray = np.ones(5)
print(numpyArray)
trch = torch.from_numpy(numpyArray)
print(trch)
## and also we must be careful that if we modify one the other will be modified
numpyArray +=1
print("numpyArray after adding: ",a)
print("tensor after adding: ", b)

from tensor to numpy
the tensor is:  tensor([1., 1., 1., 1., 1.])
the numpy array is:  [1. 1. 1. 1. 1.]
a after adding:  tensor([2., 2., 2., 2., 2.])
b after adding:  [2. 2. 2. 2. 2.]
##########################################
from numpy to tensor
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
numpyArray after adding:  tensor([2., 2., 2., 2., 2.])
tensor after adding:  [2. 2. 2. 2. 2.]


## using GPU

In [42]:
if torch.cuda.is_available():
    gpu_device = torch.device("cuda")
    x = torch.ones(5, device = gpu_device)
    y = torch.ones(5)
    y = y.to(gpu_device) # to use y in gpu
    z = x - y
    print(z)
    print(type(z))
    # z.numpy() it won't work because numpy can handle cpu tensors only 
    #### we have to convert it to cpu tensor 
    # z = z.to("cpu")
    # z.numpy()

tensor([0., 0., 0., 0., 0.], device='cuda:0')
<class 'torch.Tensor'>


### requires_grad attribute

In [43]:
x = torch.ones(5, requires_grad=True)
print(x)
# requires_grad will tell the pytorch that we need to calculate the gradient 
# for this tensor later and we use it in an optimization steps problems
 

tensor([1., 1., 1., 1., 1.], requires_grad=True)
