In [2]:
import torch

### requires_grad will tell the pytorch that we need to calculate the gradient  for this tensor we use itlater  in an optimization steps problems

In [21]:
x = torch.rand(3, requires_grad = True)
print(x)
y = 2 + x
print(y)
z = y * y * 2
print(z)
z = z.mean()
print(z)

tensor([0.1194, 0.7722, 0.6958], requires_grad=True)
tensor([2.1194, 2.7722, 2.6958], grad_fn=<AddBackward0>)
tensor([ 8.9839, 15.3703, 14.5347], grad_fn=<MulBackward0>)
tensor(12.9629, grad_fn=<MeanBackward0>)


#### when we want to calculate the gradient

In [22]:
z.backward() # will calculate dz/dx
# now x will have gradient
print(x.grad)

tensor([2.8259, 3.6963, 3.5944])


#### imagine that we finished our computation and we need to use the results in other things so we don't need pytorch to keep calculating the gradient so we need to stop calculating the gradient

In [24]:
# we can do this by using

# first method is:
x.requires_grad_(False)
print(x)

x = torch.randn(3, requires_grad = True)
print(x)

# second method is:
y = x.detach()
print(y)

tensor([ 0.1647, -0.6320, -1.4574])
tensor([ 0.9442, -2.8238,  1.1483], requires_grad=True)
tensor([ 0.9442, -2.8238,  1.1483])


#### whenever we called the backward function then the gradient for this tensor will be accumlated into the .grad attribute which something that we don't want to happen let's see the problem and how to solve it

In [25]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])


In [26]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [27]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


the problem is the tensor is accumulating the values is summing up so our weights or gradiens is incorrect
to solve this we must empty the gradient

In [28]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    # to solve the problem
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# pytorch optimizers

In [ ]:
optimizer = torch.optim.SGD(weights, lr=0.1)
optimizer.step()
# before we do the next iteration we will do which will clear the gradient at each iteration
optimizer.zero_grad()